name: Mark Stale Issues

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: Mark stale issues and PRs
        uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: stale
          stale-pr-label: stale
          stale-issue-message: "This issue has been marked as stale because it has had no activity for 30 days."
          stale-pr-message: "This PR has been marked as stale because it has had no activity for 30 days."
